/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Changelog: typeof import('./../components/Changelog.vue')['default']
    Footer: typeof import('./../popup/layout/Footer.vue')['default']
    Header: typeof import('./../popup/layout/Header.vue')['default']
    IIcBaselineWbSunny: typeof import('~icons/ic/baseline-wb-sunny')['default']
    IIcOutlineRemoveRedEye: typeof import('~icons/ic/outline-remove-red-eye')['default']
    IMdiAccount: typeof import('~icons/mdi/account')['default']
    IMdiAlertCircleOutline: typeof import('~icons/mdi/alert-circle-outline')['default']
    IMdiCog: typeof import('~icons/mdi/cog')['default']
    IMdiFileSearchOutline: typeof import('~icons/mdi/file-search-outline')['default']
    IMdiInformationSlabCircleOutline: typeof import('~icons/mdi/information-slab-circle-outline')['default']
    IMdiLinkVariant: typeof import('~icons/mdi/link-variant')['default']
    IMdiLogout: typeof import('~icons/mdi/logout')['default']
    IMdiPoliceBadgeOutline: typeof import('~icons/mdi/police-badge-outline')['default']
    IMdiWeatherNight: typeof import('~icons/mdi/weather-night')['default']
    Install: typeof import('./../components/install.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Update: typeof import('./../components/update.vue')['default']
  }
}
